export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGGEDIN = "USER_LOGGEDIN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const LOADING_WORKSPACES = "LOADING_WORKSPACES";
export const WORKSPACES_RECEIVED = "WORKSPACES_RECEIVED";
export const SET_SELECTED_WORKSPACE = "SET_SELECTED_WORKSPACE";
export const UPDATE_WORKSPACE_PROJECT_DELETE = "UPDATE_WORKSPACE_PROJECT_DELETE";

export const LOADING_PROJECTS = "LOADING_PROJECTS";
export const PROJECTS_RECEIVED = "PROJECTS_RECEIVED";
export const TOGGLE_SHOW_ADD_PROJECT_MODAL = "TOGGLE_SHOW_ADD_PROJECT_MODAL";
export const ACTIVE_PROJECT = "ACTIVE_PROJECT";
export const PROJECT_UPDATED = "PROJECT_UPDATED";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const LOADING_TASKS = "LOADING_TASKS";
export const TASKS_RECEIVED = "TASKS_RECEIVED";
export const TASK_UPDATED = "TASK_UPDATED";
export const TASK_DELETED = "TASK_DELETED";